apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: myapp1
  name:
    podwithsamelabelasrs
spec:
  containers:
  -  name: mycont
     image: lerndevops/samplepyapp:v1
     ports:
     -  containerPort: 3000
