kind: Deployment
apiVersion: apps/v1
metadata:
  name: vcababatatadeployment
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      client: babatata
  template:
    metadata:
      labels:
        client: babatata
    spec:
      containers:
      - image: vcababatata/vhttpnode:v1
        name: nodejs
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata: 
  name: vcababatataservice
spec: 
  type: NodePort
  selector:
    client: babatata
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32303


